//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing;

namespace ProjectX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap MainHero =>
            (System.Drawing.Bitmap)ResourceManager.GetObject("MainHero", resourceCulture);

        internal static System.Drawing.Bitmap Bush {
            get {
                object obj = ResourceManager.GetObject("Bush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Buba0 {
            get {
                object obj = ResourceManager.GetObject("Buba0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Buba1 {
            get {
                object obj = ResourceManager.GetObject("Buba1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buba2 {
            get {
                object obj = ResourceManager.GetObject("Buba2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buba3 {
            get {
                object obj = ResourceManager.GetObject("Buba3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buba4 {
            get {
                object obj = ResourceManager.GetObject("Buba4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buba5 {
            get {
                object obj = ResourceManager.GetObject("Buba5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeadHero {
            get {
                object obj = ResourceManager.GetObject("DeadHero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Enemy {
            get {
                object obj = ResourceManager.GetObject("Enemy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static string EnemyDamage
        {
            get { return ResourceManager.GetString("EnemyDamage", resourceCulture); }
        }
        
        internal static string EnemySpeed {
            get {
                return ResourceManager.GetString("EnemySpeed", resourceCulture);
            }
        }

        internal static string EnergyCount {
            get {
                return ResourceManager.GetString("EnergyCount", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap EnergyBonus {
            get {
                object obj = ResourceManager.GetObject("EnergyBonus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static string EnergyBonusValue {
            get {
                return ResourceManager.GetString("EnergyBonusValue", resourceCulture);
            }
        }

        internal static string SpawnLocationMax {
            get {
                return ResourceManager.GetString("SpawnLocationMax", resourceCulture);
            }
        }
        
        internal static string SpawnLocationMin {
            get {
                return ResourceManager.GetString("SpawnLocationMin", resourceCulture);
            }
        }

        internal static string HeroStartHealth {
            get {
                return ResourceManager.GetString("HeroStartHealth", resourceCulture);
            }
        }
        
        internal static string HeroStartSpeed {
            get {
                return ResourceManager.GetString("HeroStartSpeed", resourceCulture);
            }
        }

        internal static string EnemyCount {
            get {
                return ResourceManager.GetString("EnemyCount", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap HealthBonus {
            get {
                object obj = ResourceManager.GetObject("HealthBonus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static string HealthBonusValue {
            get {
                return ResourceManager.GetString("HealthBonusValue", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap PoisonBerry {
            get {
                object obj = ResourceManager.GetObject("PoisonBerry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static string BonusCount {
            get {
                return ResourceManager.GetString("BonusCount", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap Interface {
            get {
                object obj = ResourceManager.GetObject("Interface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap InputInstrucion {
            get {
                object obj = ResourceManager.GetObject("InputInstrucion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DeathScreen {
            get {
                object obj = ResourceManager.GetObject("DeathScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap WinScreen {
            get {
                object obj = ResourceManager.GetObject("WinScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Rule0 {
            get {
                object obj = ResourceManager.GetObject("Rule0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rule1 {
            get {
                object obj = ResourceManager.GetObject("Rule1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rule2 {
            get {
                object obj = ResourceManager.GetObject("Rule2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rule3 {
            get {
                object obj = ResourceManager.GetObject("Rule3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rule4 {
            get {
                object obj = ResourceManager.GetObject("Rule4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rule5 {
            get {
                object obj = ResourceManager.GetObject("Rule5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static string TimeBonusValue {
            get {
                return ResourceManager.GetString("TimeBonusValue", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap AngryMushroom {
            get {
                object obj = ResourceManager.GetObject("AngryMushroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
